development:
  adapter: mysql2
  encoding: utf8
  database: rmap_development
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  database: rmap_test
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rmap
  pool: 5
  username: root
  password: 
