mobile_id: on

full_host: http://resmap-stg-ilab.instedd.org
host: resmap-stg-ilab.instedd.org
number_of_attempt_failed: 5
default_mail_sender: noreply@ilabsea.org
devise_mail_sender: resourcemap@ilabsea.org
mandrill_username: "resourcesmap@ilabsea.org"
mandrill_password: "YkXyniE49DI4vmmB1FbdNg"
max_aggregate_result_size: 500
notify_alert: on
app_name: 'resourcemap-program-assessment'

plugins:
  public_collection: on
  snapshot: on
  channels: on
  reminders: on
  alerts: on
  account_completeness: on
  fred_api: on
